# general settings for CAR training
name: ART_CAR_q40
model_type: ARTModel
scale: 1
num_gpu: 4
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: CAR
    name: DFWB_CAR
    type: PairedImageDataset
    dataroot_gt: datasets/DFWB_CAR/HQ
    dataroot_lq: datasets/DFWB_CAR/LQ/40
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 126
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    task: CAR
    name: Classic5
    type: PairedImageDataset
    dataroot_gt: datasets/CAR/Classic5/Classic5_HQ
    dataroot_lq: datasets/CAR/Classic5/Classic5_LQ/40
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: ART
  upscale: 1
  in_chans: 1
  img_size: 126
  window_size: 7
  img_range: 255.
  depths: [6, 6, 6, 6, 6, 6]
  interval: [18, 18, 13, 13, 7, 7]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4 # for jpeg 40
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 800000, 1200000, 1400000, 1500000 ] # for jpeg 40
    gamma: 0.5

  total_iter: 1600000 # for jpeg 40
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean
    eps: !!float 1e-3

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
