# general settings for ColorDN training
name: ART_ColorDN_level15
model_type: ARTModel
scale: 1
num_gpu: 4
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    task: denoising_color
    noise: 15 # 15/25/50
    name: DFWB_RGB
    type: PairedImageDataset
    dataroot_gt: datasets/DFWB_RGB/HQ
    dataroot_lq: datasets/DFWB_RGB/HQ
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  val:
    task: denoising_color
    noise: 15 # 15/25/50
    name: McMaster
    type: PairedImageDataset
    dataroot_gt: datasets/ColorDN/McMasterHQ
    dataroot_lq: datasets/ColorDN/McMasterHQ
    filename_tmpl: '{}'
    io_backend:
      type: disk

# network structures
network_g:
  type: ART
  upscale: 1
  in_chans: 3
  img_size: 128
  window_size: 8
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  interval: [16, 16, 12, 12, 8, 8]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 4


path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4 # for noise 15
#    lr: !!float 1e-4 # for noise 25/50
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 800000, 1200000, 1400000, 1500000 ] # for noise 15
#    milestones: [ 400000, 600000, 700000, 750000 ] # for noise 25/50
    gamma: 0.5

  total_iter: 1600000 # for noise 15
#  total_iter: 800000 # for noise 25/50
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean
    eps: !!float 1e-3

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 2e4
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500